//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraySystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookIssue
    {
        public int IssueId { get; set; }
        public Nullable<int> RequestId { get; set; }
        public Nullable<int> BookId { get; set; }
        public Nullable<int> BookAmount { get; set; }
        public System.DateTime IssueDate { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public Nullable<bool> IssueStatus { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual BookRequest BookRequest { get; set; }
    }
}
