//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraySystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookRequest()
        {
            this.BookIssues = new HashSet<BookIssue>();
        }
    
        public int RequestId { get; set; }
        public Nullable<int> MemberId { get; set; }
        public Nullable<int> StaffId { get; set; }
        public Nullable<int> RequestBookTotal { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookIssue> BookIssues { get; set; }
        public virtual Member Member { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
